# Generated by Django 3.1.7 on 2021-03-05 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210305_0923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='user',
            new_name='author',
        ),
    ]
