# Generated by Django 3.1.7 on 2021-03-04 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_delete_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='title',
            new_name='name',
        ),
    ]
