# Generated by Django 3.1.7 on 2021-03-05 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210305_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_id',
            new_name='id',
        ),
    ]
